/* === Privacy in Practice — artefact library data === */

window.ARTEFACTS = [
  {
    id: "dsar-pack",
    title: "DSAR handling pack",
    area: "dp",
    kicker: "Data Protection · Operations",
    status: "available",
    summary: "A complete set of templates and a one-page methodology covering the lifecycle of a Data Subject Access Request — from receipt through response.",
    why: "DSARs are one of the most common operational tasks for a DPO and one of the most consistent sources of regulatory complaints. Most firms manage them in ad-hoc inboxes. This pack is the artefact you'd produce on day one of a new role.",
    contents: [
      "DSAR acknowledgement letter (use within 7 days of receipt)",
      "Identity verification request — minimal-data version",
      "Scope confirmation template (where the request is ambiguous)",
      "Third-party redaction matrix with the reasonableness test",
      "Standard response letter with the Article 15 disclosure list",
      "Manifestly-unfounded / excessive refusal template",
      "DSAR log entry — one row per request, audit-ready",
    ],
    formats: ["PDF", "DOCX"],
    notes: "All template language is mine — feel free to copy, adapt, distribute. Citations to ICO guidance throughout.",
  },
  {
    id: "dpia-worked",
    title: "DPIA — worked example",
    area: "dp",
    kicker: "Data Protection · DPIAs",
    status: "available",
    summary: "A full Article 35-compliant DPIA on a hypothetical employee-monitoring system. Real risk-register entries, real mitigations, real residual-risk decisions.",
    why: "Every DP interview asks if you've done a DPIA. Saying 'I read the ICO template' isn't an answer. Sharing a completed worked example with reasoning is.",
    contents: [
      "Description of processing — purposes, lawful basis, data flows",
      "Necessity and proportionality assessment",
      "Risk register — 14 entries with likelihood × impact scoring",
      "Mitigation measures (technical + organisational)",
      "Residual risk position and prior-consultation analysis",
      "Sign-off log and review schedule",
      "What I'd do differently — a short retrospective at the end",
    ],
    formats: ["PDF", "DOCX"],
    notes: "Hypothetical scenario — no real employer named. Designed to be readable by a non-lawyer hiring manager.",
  },
  {
    id: "breach-playbook",
    title: "Personal data breach playbook",
    area: "dp",
    kicker: "Data Protection · Incidents",
    status: "available",
    summary: "The decision tree, decision log, and notification templates I'd want available at 5am on a Saturday when a breach is reported.",
    why: "The 72-hour clock starts at AWARENESS, not at containment. A playbook means the first hour is spent doing the right things rather than working out what they are.",
    contents: [
      "Awareness-trigger flow — what counts as the start of the clock",
      "Containment checklist (organised by attack type)",
      "Severity assessment matrix — when to escalate to the DPO",
      "ICO Article 33 notification template (with all required fields)",
      "Individual Article 34 communication template, plain English",
      "Internal stakeholder cascade — who learns what, when",
      "Post-incident review template with root-cause framing",
    ],
    formats: ["PDF", "DOCX"],
    notes: "Built for a small-medium organisation. Larger firms will need additional approval routes; the structure scales.",
  },
  {
    id: "ropa-template",
    title: "ROPA template — controller + processor",
    area: "dp",
    kicker: "Data Protection · Accountability",
    status: "soon",
    summary: "Article 30 records of processing activities, in both controller and processor versions, with worked examples for HR, customer service, and marketing.",
    why: "ROPAs are the foundation of accountability. Most starter ROPAs are bloated spreadsheets. This one is the minimum required information, organised for readability.",
    contents: [
      "Controller ROPA template (7 mandatory fields)",
      "Processor ROPA template (6 mandatory fields)",
      "Three populated example rows for context",
      "Linked privacy-notice cross-reference",
      "Suggested governance cadence and ownership matrix",
    ],
    formats: ["XLSX", "PDF"],
    notes: "Coming next: I'm finalising the worked rows. Sign up to the newsletter to know when it lands.",
  },
  {
    id: "privacy-notice",
    title: "Privacy notice — annotated rewrite",
    area: "dp",
    kicker: "Data Protection · Transparency",
    status: "soon",
    summary: "A real public privacy notice rewritten in plain English with side-by-side commentary on the changes.",
    why: "Most privacy notices are unreadable. This artefact demonstrates Article 13/14 fluency by SHOWING the gap, not describing it.",
    contents: [
      "Original notice (anonymised)",
      "Rewritten layered notice — top layer + detailed layer",
      "Commentary block per change",
      "Linked Article 13/14 mapping",
    ],
    formats: ["PDF"],
    notes: "Will land alongside an article explaining the methodology.",
  },
  {
    id: "ai-risk",
    title: "AI risk assessment — worked example",
    area: "ai",
    kicker: "AI Governance · Risk",
    status: "soon",
    summary: "Combined GDPR Article 35 + EU AI Act risk assessment on a hypothetical LLM-based customer-support assistant.",
    why: "AI governance roles consistently ask for this artefact. The combined methodology is what distinguishes AI-Act-fluent practitioners from privacy-only ones.",
    contents: [
      "Use case description + data flow diagram",
      "AI Act risk class analysis with reasoning",
      "GDPR Article 22 analysis",
      "Training-data lineage and special-category exposure",
      "Mitigations — technical, organisational, contractual",
      "Go / no-go recommendation and review schedule",
    ],
    formats: ["PDF", "DOCX"],
    notes: "Building this alongside ISO 42001 implementation work — will reflect best practice as of mid-2026.",
  },
];
