/* === Privacy in Practice — books / reading list ===
   Curated reading list across all 6 practice areas.

   Each entry has spine dimensions (height + width) and a colour drawn from
   the site's area palette, so the bookcase renders as a realistic shelf
   with varied heights and shades. */

window.BOOKS = [
  /* ─── Foundational / general ─────────────────────────────────── */
  {
    id: "zuboff-surveillance",
    location: "shelf",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781610395694-L.jpg",
    title: "The Age of Surveillance Capitalism",
    spineLabel: "The Age of Surveillance Capitalism",
    author: "Shoshana Zuboff",
    authorShort: "Zuboff",
    year: 2019,
    type: "Book",
    format: "Trade paperback",
    area: "general",
    color: "plum",
    h: 340, w: 64,
    tilt: -4,
    featured: true,
    summary: "The defining account of how 'behavioural surplus' became the most valuable commodity of the digital economy. Long, dense, and worth every page.",
    why: "Anyone doing data protection work without an opinion on Zuboff is missing the deepest argument about why this profession exists. The book is exhausting in the best way; you'll never look at a privacy policy the same way after reading it.",
    url: "https://shoshanazuboff.com/book/about/",
  },
  {
    id: "cavoukian-pbd",
    location: "shelf",
    title: "Privacy by Design — The 7 Foundational Principles",
    spineLabel: "Privacy by Design · 7 Principles",
    author: "Ann Cavoukian",
    authorShort: "Cavoukian",
    year: 2011,
    type: "Paper",
    format: "Free PDF",
    area: "dp",
    color: "lavender",
    h: 260, w: 50,
    tilt: 5,
    featured: true,
    summary: "The original PbD paper. 13 pages. Every modern privacy framework — including GDPR's Article 25 — owes a direct intellectual debt to this document.",
    why: "Practical, short, and quotable. You'll cite it in your DPIAs, your policies, and your interviews. Free.",
    url: "https://www.ipc.on.ca/wp-content/uploads/resources/7foundationalprinciples.pdf",
  },
  {
    id: "carey-uk-law",
    location: "shelf",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780198812198-L.jpg",
    title: "Data Protection: A Practical Guide to UK Law",
    spineLabel: "DP — A Practical Guide to UK Law",
    author: "Peter Carey",
    authorShort: "Carey",
    year: 2024,
    type: "Book",
    format: "Hardback (OUP)",
    area: "dp",
    color: "blush",
    h: 320, w: 70,
    featured: false,
    summary: "Oxford's standard UK DP textbook. Encyclopaedic but readable; covers UK GDPR, DPA 2018, PECR, and the law of confidence in one place.",
    why: "The book to keep on your desk. When you need to know what the law actually says — not what the ICO blog says about what the law might mean — this is the reference.",
    url: "https://global.oup.com/academic/product/data-protection-9780198812198",
  },
  {
    id: "ico-guide",
    location: "web",
    title: "ICO Guide to UK GDPR",
    spineLabel: "ICO Guide to UK GDPR",
    author: "Information Commissioner's Office",
    authorShort: "ICO",
    year: 2024,
    type: "Reference",
    format: "Free online",
    area: "dp",
    color: "sun",
    h: 280, w: 56,
    featured: true,
    summary: "The regulator's official, public, frequently-updated interpretation of UK GDPR. Treat it as a living document.",
    why: "If you cite this in a board paper and you're wrong, the regulator was wrong with you. That's the strongest defensive position in DP practice.",
    url: "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/",
  },
  {
    id: "itgp-implementation",
    location: "shelf",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9781787783904-L.jpg",
    title: "EU GDPR: An Implementation & Compliance Guide",
    spineLabel: "GDPR Implementation & Compliance",
    author: "IT Governance Publishing",
    authorShort: "ITGP",
    year: 2020,
    type: "Book",
    format: "Paperback",
    area: "dp",
    color: "mint",
    h: 300, w: 60,
    summary: "Operational counterpart to the legal textbooks. Less 'what does Article 6 mean'; more 'what should our intake form look like'.",
    why: "Good for the early-career practitioner who needs to ship something on Monday, not understand Recital 71 by Friday.",
    url: "https://www.itgovernancepublishing.co.uk/product/eu-general-data-protection-regulation-gdpr-an-implementation-and-compliance-guide",
  },

  /* ─── AI Governance ─────────────────────────────────────────── */
  {
    id: "ai-snake-oil",
    location: "shelf",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780691249131-L.jpg",
    title: "AI Snake Oil",
    spineLabel: "AI Snake Oil",
    author: "Arvind Narayanan & Sayash Kapoor",
    authorShort: "Narayanan & Kapoor",
    year: 2024,
    type: "Book",
    format: "Hardback",
    area: "ai",
    color: "lavender",
    h: 290, w: 58,
    tilt: -3,
    featured: true,
    summary: "Sceptical, evidence-based account of where AI works, where it doesn't, and where vendors lie about it.",
    why: "Indispensable for spotting nonsense in AI procurement. Pair with their Substack for the latest examples.",
    url: "https://www.aisnakeoil.com/",
  },
  {
    id: "ai-act-explorer",
    location: "web",
    title: "EU AI Act Explorer",
    spineLabel: "EU AI Act Explorer",
    author: "Future of Life Institute",
    authorShort: "FLI",
    year: 2024,
    type: "Reference",
    format: "Free online",
    area: "ai",
    color: "blush",
    h: 270, w: 52,
    summary: "Searchable, cross-referenced version of the AI Act. The fastest way to navigate the Act without losing your mind.",
    why: "Use it. Bookmark it. Cite it in your AI risk assessments. The actual Act is hard to read; this is the practical entry point.",
    url: "https://artificialintelligenceact.eu/",
  },
  {
    id: "nist-ai-rmf",
    location: "shelf",
    title: "NIST AI Risk Management Framework",
    spineLabel: "NIST AI Risk Management Framework",
    author: "NIST",
    authorShort: "NIST",
    year: 2023,
    type: "Standard",
    format: "Free PDF",
    area: "ai",
    color: "ocean",
    h: 310, w: 62,
    summary: "Voluntary US framework for AI risk management. Four core functions: Govern, Map, Measure, Manage.",
    why: "Increasingly the language of enterprise AI procurement, including in the UK. Mastery of the Playbook is becoming table-stakes for AI governance roles.",
    url: "https://www.nist.gov/itl/ai-risk-management-framework",
  },
  {
    id: "import-ai",
    location: "web",
    title: "Import AI",
    spineLabel: "Import AI · Jack Clark",
    author: "Jack Clark",
    authorShort: "Clark",
    year: 2024,
    type: "Newsletter",
    format: "Free weekly",
    area: "ai",
    color: "sun",
    h: 250, w: 48,
    summary: "Weekly industry digest. The 'why this matters' section is where most of the practical insight lives.",
    why: "Best single signal for keeping current on the global AI industry. Read it for ten minutes on Sunday.",
    url: "https://importai.substack.com/",
  },

  /* ─── FinTech ───────────────────────────────────────────────── */
  {
    id: "fca-handbook",
    location: "web",
    title: "FCA Handbook",
    spineLabel: "FCA Handbook",
    author: "Financial Conduct Authority",
    authorShort: "FCA",
    year: 2026,
    type: "Reference",
    format: "Free online",
    area: "fintech",
    color: "sun",
    h: 330, w: 68,
    featured: true,
    summary: "The UK's financial-services rulebook. PRIN, SYSC, COBS, CASS, CONC, DISP — and dozens more.",
    why: "Primary source. Subscribe to email alerts on the chapters relevant to your firm. The only people who don't read the Handbook are the ones who get caught not reading it.",
    url: "https://www.handbook.fca.org.uk/",
  },
  {
    id: "fca-ceo-letters",
    location: "web",
    title: "Dear CEO Letters",
    spineLabel: "FCA Dear CEO Letters",
    author: "FCA",
    authorShort: "FCA",
    year: 2026,
    type: "Reference",
    format: "Free",
    area: "fintech",
    color: "mint",
    h: 280, w: 54,
    summary: "Sector-wide letters from the FCA setting out concerns and supervisory expectations. The clearest live signal of where enforcement is heading.",
    why: "Read every Dear CEO letter in your sector. They tell you what supervisory visits will ask about for the next 12 months.",
    url: "https://www.fca.org.uk/firms/dear-ceo-letters",
  },
  {
    id: "fintech-brainfood",
    location: "web",
    title: "Fintech Brainfood",
    spineLabel: "Fintech Brainfood · Simon Taylor",
    author: "Simon Taylor",
    authorShort: "Taylor",
    year: 2024,
    type: "Newsletter",
    format: "Free weekly",
    area: "fintech",
    color: "blush",
    h: 260, w: 50,
    summary: "Operator's-view newsletter on the global fintech industry. Long, opinionated, useful.",
    why: "The single best newsletter for understanding fintech business models in addition to regulation. Pair it with the FCA Handbook for theory + practice.",
    url: "https://www.fintechbrainfood.com/",
  },

  /* ─── Cybersecurity ─────────────────────────────────────────── */
  {
    id: "krebs",
    location: "web",
    title: "Krebs on Security",
    spineLabel: "Krebs on Security",
    author: "Brian Krebs",
    authorShort: "Krebs",
    year: 2024,
    type: "Blog",
    format: "Free",
    area: "cyber",
    color: "mint",
    h: 270, w: 52,
    featured: true,
    summary: "Investigative security journalism. The single most-cited security blog in English.",
    why: "Where breach investigations get traced back to root cause. Vendor-independent; rare in this space.",
    url: "https://krebsonsecurity.com/",
  },
  {
    id: "ncsc-threat",
    location: "web",
    title: "NCSC Weekly Threat Report",
    spineLabel: "NCSC Weekly Threat Report",
    author: "National Cyber Security Centre",
    authorShort: "NCSC",
    year: 2026,
    type: "Report",
    format: "Free weekly",
    area: "cyber",
    color: "ocean",
    h: 290, w: 56,
    summary: "The UK's official threat-landscape snapshot. Concise, practical, and aimed at boards as much as analysts.",
    why: "Read every Friday for half an hour. Quote it in board papers. Take its advisory recommendations seriously.",
    url: "https://www.ncsc.gov.uk/section/keep-up-to-date/threat-reports",
  },
  {
    id: "iso-27001",
    location: "shelf",
    title: "ISO/IEC 27001:2022",
    spineLabel: "ISO/IEC 27001:2022",
    author: "ISO",
    authorShort: "ISO",
    year: 2022,
    type: "Standard",
    format: "Paid",
    area: "cyber",
    color: "lavender",
    h: 320, w: 64,
    summary: "International standard for Information Security Management Systems. The de-facto enterprise baseline.",
    why: "Not light reading — but essential reference for anyone running or auditing an ISMS. The 2022 update simplified Annex A significantly.",
    url: "https://www.iso.org/standard/27001",
  },
  {
    id: "risky-biz",
    location: "web",
    title: "Risky Business",
    spineLabel: "Risky Business · Patrick Gray",
    author: "Patrick Gray",
    authorShort: "Gray",
    year: 2024,
    type: "Podcast",
    format: "Free + paid",
    area: "cyber",
    color: "sun",
    h: 240, w: 46,
    summary: "Weekly security podcast with an operator's tone. Cuts through marketing noise more honestly than most.",
    why: "Listen on a commute. Mix of news, analysis, and product reviews — the news segments are the highest-density 30 minutes in cyber.",
    url: "https://risky.biz/",
  },

  /* ─── Conduct ───────────────────────────────────────────────── */
  {
    id: "fca-cd-hub",
    location: "web",
    title: "FCA Consumer Duty Hub",
    spineLabel: "FCA Consumer Duty Hub",
    author: "FCA",
    authorShort: "FCA",
    year: 2026,
    type: "Reference",
    format: "Free",
    area: "conduct",
    color: "coral",
    h: 290, w: 58,
    featured: true,
    summary: "The regulator's central resource on Consumer Duty implementation. Updated frequently with multi-firm review findings.",
    why: "Where supervisory expectation about Consumer Duty actually lives. Re-read quarterly; the bar shifts.",
    url: "https://www.fca.org.uk/firms/consumer-duty",
  },
  {
    id: "fos-data",
    location: "web",
    title: "FOS Annual Complaints Data",
    spineLabel: "FOS Annual Complaints Data",
    author: "Financial Ombudsman Service",
    authorShort: "FOS",
    year: 2026,
    type: "Report",
    format: "Free",
    area: "conduct",
    color: "lavender",
    h: 270, w: 52,
    summary: "Year-by-year breakdown of where customer disputes occur. Granular by firm and product type.",
    why: "The empirical map of consumer-treatment failure. If you're doing root-cause work, this is your starting point.",
    url: "https://www.financial-ombudsman.org.uk/data-insight",
  },
  {
    id: "money-mental-health",
    location: "web",
    title: "Money & Mental Health Reports",
    spineLabel: "Money & Mental Health Policy Institute",
    author: "Money & Mental Health Policy Institute",
    authorShort: "MMHPI",
    year: 2024,
    type: "Report",
    format: "Free",
    area: "conduct",
    color: "blush",
    h: 280, w: 54,
    summary: "Foundational UK research on vulnerable customers, especially around financial harm and mental health.",
    why: "Citations from MMHPI carry weight with FCA. Builds the evidence base for vulnerable-customer programmes.",
    url: "https://www.moneyandmentalhealth.org/",
  },

  /* ─── AML / Financial Crime ─────────────────────────────────── */
  {
    id: "fatf-mer",
    location: "shelf",
    title: "UK Mutual Evaluation Report",
    spineLabel: "FATF UK Mutual Evaluation",
    author: "Financial Action Task Force",
    authorShort: "FATF",
    year: 2018,
    type: "Report",
    format: "Free PDF",
    area: "aml",
    color: "ocean",
    h: 330, w: 66,
    tilt: 4,
    featured: true,
    summary: "FATF's evaluation of the UK's AML/CTF/CPF regime. Lengthy, technical, and the single most-cited document in UK AML policy work.",
    why: "Every MLRO should have read at least the executive summary. Sets the framework against which UK enforcement is measured.",
    url: "https://www.fatf-gafi.org/en/publications/Mutualevaluations/Mer-united-kingdom-2018.html",
  },
  {
    id: "browder-red-notice",
    location: "shelf",
    coverUrl: "https://covers.openlibrary.org/b/isbn/9780552170321-L.jpg",
    title: "Red Notice",
    spineLabel: "Red Notice",
    author: "Bill Browder",
    authorShort: "Browder",
    year: 2015,
    type: "Book",
    format: "Paperback",
    area: "aml",
    color: "coral",
    h: 300, w: 58,
    tilt: -5,
    summary: "First-person account of the Magnitsky case. Surprisingly readable practical foundation for understanding kleptocracy and sanctions.",
    why: "Makes complex sanctions geopolitics legible. Quoted in many UK sanctions trainings; worth reading first-hand.",
    url: "https://www.harpercollins.co.uk/9780552170321/red-notice/",
  },
  {
    id: "rusi-financial-crime",
    location: "web",
    title: "RUSI Centre for Financial Crime",
    spineLabel: "RUSI Centre for Financial Crime",
    author: "RUSI",
    authorShort: "RUSI",
    year: 2024,
    type: "Research",
    format: "Free",
    area: "aml",
    color: "sun",
    h: 280, w: 54,
    summary: "Britain's best think-tank coverage of financial-crime policy. Especially strong on sanctions and SARs reform.",
    why: "Where the policy debate around UK AML actually happens. Cite them in your briefings.",
    url: "https://www.rusi.org/explore-our-research/research-groups/centre-financial-crime-and-security-studies",
  },
  {
    id: "ofsi-guidance",
    location: "web",
    title: "OFSI Sanctions Guidance",
    spineLabel: "OFSI Sanctions Guidance",
    author: "OFSI / HM Treasury",
    authorShort: "OFSI",
    year: 2026,
    type: "Reference",
    format: "Free",
    area: "aml",
    color: "mint",
    h: 290, w: 56,
    summary: "Primary source for UK financial sanctions implementation, licensing, and breach reporting.",
    why: "Sanctions is the highest-shortage area in UK compliance right now. Mastering OFSI's guidance is a near-immediate hireable signal.",
    url: "https://www.gov.uk/government/organisations/office-of-financial-sanctions-implementation",
  },
];
