/* === Privacy in Practice — glossary data === */

window.GLOSSARY = [
  // Privacy / DP
  { term: "Article 5", area: "dp", short: "The seven UK GDPR principles.", long: "Lawfulness, fairness & transparency · purpose limitation · data minimisation · accuracy · storage limitation · integrity & confidentiality · accountability. The accountability principle (Art 5(2)) is the practical one — you must be able to DEMONSTRATE compliance with the other six." },
  { term: "Article 6", area: "dp", short: "Lawful bases for processing.", long: "The six lawful bases: consent · contract · legal obligation · vital interests · public task · legitimate interests. At least one must apply to any processing of personal data." },
  { term: "Article 9", area: "dp", short: "Special category data — the two-key rule.", long: "Processing special category data needs an Article 9 condition IN ADDITION to an Article 6 lawful basis. Ten categories: racial/ethnic origin, political opinions, religious/philosophical beliefs, trade union membership, genetic, biometric (for ID), health, sex life, sexual orientation." },
  { term: "Article 22", area: "dp", short: "Right not to be subject to solely-automated decisions.", long: "Where the decision produces legal or similarly significant effects. Article 22 has three exceptions (necessary for contract, authorised by law, explicit consent) and requires safeguards including human intervention and the right to contest." },
  { term: "Article 25", area: "dp", short: "Data protection by design and by default.", long: "Controllers must implement appropriate technical & organisational measures from the outset, AND ensure that by default only personal data necessary for each purpose is processed." },
  { term: "Article 28", area: "dp", short: "Controller / processor contracts.", long: "Processors can only be engaged under a WRITTEN contract that covers eight specific matters: subject matter, duration, nature/purpose, type of data, categories of subjects, controller's rights/obligations, plus the processor's eight specific obligations (instructions, confidentiality, security, sub-processors, rights assistance, deletion, audit, alert)." },
  { term: "Article 30", area: "dp", short: "Records of Processing Activities (ROPAs).", long: "Controllers and processors must maintain written records of their processing activities. Controller ROPAs list 7 things; processor ROPAs list 6." },
  { term: "Article 32", area: "dp", short: "Security of processing.", long: "Implement appropriate technical and organisational measures considering state of the art, costs, scope, and risks. Examples: pseudonymisation, encryption, ongoing CIA assurance, regular testing." },
  { term: "Article 33", area: "dp", short: "The 72-hour breach notification rule.", long: "Notify the ICO of personal data breaches within 72 hours of becoming AWARE, unless unlikely to result in a risk to rights and freedoms. Awareness ≠ when the breach happened — it's when you reasonably know personal data has been compromised." },
  { term: "Article 34", area: "dp", short: "Telling affected individuals about a breach.", long: "Required when the breach is likely to result in HIGH risk to rights and freedoms. Three exceptions: encryption renders data unintelligible, subsequent measures eliminate the risk, or disproportionate effort (use public communication instead)." },
  { term: "Article 35", area: "dp", short: "Data Protection Impact Assessment.", long: "A DPIA is mandatory when processing is likely to result in high risk. Specifically: systematic & extensive profiling with significant effects, large-scale special category data, or systematic monitoring of publicly accessible areas at scale." },
  { term: "Article 37", area: "dp", short: "When you must appoint a DPO.", long: "Mandatory if: (a) public authority/body, (b) core activities require regular & systematic monitoring of data subjects at scale, or (c) core activities involve large-scale processing of special category or criminal offence data." },
  { term: "DPIA", area: "dp", short: "Data Protection Impact Assessment.", long: "Structured assessment of risks to rights and freedoms arising from processing. Required by Article 35 in some cases, good practice in many others. Must include: description of processing, necessity & proportionality, risks, and mitigations." },
  { term: "DSAR", area: "dp", short: "Data Subject Access Request.", long: "An individual's request to access their personal data. Must be responded to within ONE MONTH (extendable by 2 months for complex requests). Response must include the data PLUS purposes, categories, recipients, retention, rights, source, automated decision-making." },
  { term: "DPO", area: "dp", short: "Data Protection Officer.", long: "Statutory role under Article 37. Independent, reports to highest level of management, can't be dismissed for performing the role. Tasks defined in Article 39." },
  { term: "ICO", area: "dp", short: "Information Commissioner's Office.", long: "UK regulator for data protection and information rights. Enforces UK GDPR, DPA 2018, PECR, EIR, and FOI. Maximum fine: £17.5m or 4% of global annual turnover." },
  { term: "PECR", area: "dp", short: "Privacy and Electronic Communications Regulations 2003.", long: "UK regulation covering electronic marketing, cookies, traffic data, and unsolicited communications. The cookies law sits here, not in UK GDPR." },
  { term: "ROPA", area: "dp", short: "Records of Processing Activities.", long: "Required by Article 30. Documents what personal data you process, why, who you share it with, retention, and security. Controller ROPAs and processor ROPAs have slightly different mandatory contents." },
  { term: "Lawful basis", area: "dp", short: "One of the six legal grounds for processing.", long: "Consent, contract, legal obligation, vital interests, public task, or legitimate interests. Must be identified BEFORE processing starts and documented in the privacy notice." },
  { term: "LIA", area: "dp", short: "Legitimate Interests Assessment.", long: "Three-part test for relying on Article 6(1)(f): purpose test (is there a legitimate interest?), necessity test (is processing needed?), balancing test (do individual's rights override?). Document the outcome." },
  { term: "TIA", area: "dp", short: "Transfer Impact Assessment.", long: "Required when relying on SCCs/IDTA for international transfers. Assesses whether the destination country's law provides essentially equivalent protection; documents safeguards." },
  { term: "IDTA", area: "dp", short: "UK International Data Transfer Agreement.", long: "Post-Brexit UK replacement for EU SCCs. Used for transfers from the UK to a 'third country' without an adequacy decision. Can be replaced by the UK Addendum to the EU SCCs." },
  { term: "SCC", area: "dp", short: "Standard Contractual Clauses.", long: "EU Commission-approved template contract clauses for transfers from the EU to third countries. Four modules: C2C, C2P, P2C, P2P. UK addendum allows use under UK GDPR." },
  { term: "Schrems II", area: "dp", short: "Landmark CJEU decision on transfers.", long: "C-311/18 (2020). Invalidated EU-US Privacy Shield; upheld SCCs but required case-by-case assessment of destination protection. Effectively created the TIA requirement." },
  { term: "Privacy notice", area: "dp", short: "Statement to data subjects under Articles 13–14.", long: "Must include identity & contacts, DPO if any, purposes, lawful basis, recipients, transfers, retention, rights, source (if not from subject), and existence of automated decision-making. Layered notices are good practice." },

  // AI Governance
  { term: "EU AI Act", area: "ai", short: "World's first comprehensive AI law.", long: "Risk-based: unacceptable / high / limited / minimal. Entered force August 2024. Prohibitions apply Feb 2025; GPAI Aug 2025; most rules Aug 2026; high-risk in regulated products Aug 2027. Extraterritorial." },
  { term: "GPAI", area: "ai", short: "General-Purpose AI models.", long: "Foundation/generative models under the EU AI Act. Providers must maintain technical documentation, publish a training-data summary, and comply with EU copyright law. Systemic-risk GPAI (above 10^25 FLOPs) has extra obligations." },
  { term: "NIST AI RMF", area: "ai", short: "Voluntary US AI risk management framework.", long: "Four core functions: Govern, Map, Measure, Manage. Not legally binding in the US but increasingly used in enterprise procurement and increasingly cited by UK firms." },
  { term: "ISO/IEC 42001", area: "ai", short: "First certifiable AI management system standard.", long: "Sets requirements for an AI Management System (AIMS). Increasingly required for enterprise procurement of AI services. Certifiable by accredited bodies." },
  { term: "AIGP", area: "ai", short: "AI Governance Professional certification.", long: "IAPP's 2024 certification covering EU AI Act, NIST AI RMF, ISO 42001, and AI risk management. Currently the most widely-recognised AI-specific cert for governance professionals." },

  // FinTech
  { term: "FCA Handbook", area: "fintech", short: "The UK's financial-services rulebook.", long: "Sections include PRIN (principles), SYSC (systems and controls), COBS (conduct), CASS (client assets), CONC (consumer credit), and DISP (complaints). Updated regularly; subscribe to alerts on relevant chapters." },
  { term: "SM&CR", area: "fintech", short: "Senior Managers and Certification Regime.", long: "Allocates personal responsibility to senior managers in FCA/PRA-regulated firms. Three tiers: Senior Manager Functions (SMFs), Certified Functions, and Conduct Rules staff. Annual fitness & propriety attestations." },
  { term: "MLR 2017", area: "fintech", short: "Money Laundering Regulations 2017.", long: "Implements the EU's 5th and 6th Anti-Money Laundering Directives in UK law. Sets out CDD requirements, beneficial ownership rules, and the cryptoasset registration regime supervised by the FCA." },
  { term: "PSD2 / Open Banking", area: "fintech", short: "Payment Services Directive 2.", long: "EU directive (retained in UK law via PSRs 2017). Created PISP, AISP, and CBPII permissions; mandated Strong Customer Authentication (SCA) and Open Banking APIs." },
  { term: "Dear CEO letter", area: "fintech", short: "FCA's clearest signal of supervisory expectation.", long: "Sector-wide letter to firms outlining concerns and expectations. Read every Dear CEO letter relevant to your sector — they're how the FCA publicly sets the supervisory bar." },
  { term: "SUP 15", area: "fintech", short: "FCA notification requirements.", long: "FCA Handbook section requiring firms to notify the regulator of significant events: breaches, fraud, civil/criminal proceedings, key changes. The notification clock is fast — often immediately." },

  // Cyber
  { term: "ISO 27001", area: "cyber", short: "Information Security Management System standard.", long: "International standard for ISMS. Certifiable by accredited bodies. Requires risk-based control selection from Annex A (now 93 controls in the 2022 update). The de-facto enterprise baseline." },
  { term: "NIS2", area: "cyber", short: "EU Network & Information Systems Directive 2.", long: "Expands NIS1 to more sectors. Two classes: 'essential' and 'important' entities. Requires 10 core security measures, 24-hour early warning + 72-hour notification, and creates management body personal liability." },
  { term: "NCSC", area: "cyber", short: "National Cyber Security Centre.", long: "UK's technical authority on cybersecurity. Part of GCHQ. Publishes the Cyber Assessment Framework (CAF), runs Cyber Essentials, and issues threat reports." },
  { term: "Cyber Essentials", area: "cyber", short: "Foundational UK cybersecurity certification.", long: "Five controls: secure configuration, boundary firewalls, access control, malware protection, security update management. Cyber Essentials Plus adds independent technical verification. Required for some government contracts." },
  { term: "CAF", area: "cyber", short: "NCSC Cyber Assessment Framework.", long: "Outcomes-based framework with four objectives, 14 principles, 39 outcomes. Used by regulators of essential services (Ofgem, OFCOM, etc.) for NIS-regulated entities." },
  { term: "SOC 2", area: "cyber", short: "Service Organization Control 2.", long: "AICPA framework. Type I assesses controls at a point in time; Type II assesses operating effectiveness over a period (usually 6–12 months). Common requirement for B2B SaaS procurement." },

  // Conduct
  { term: "Consumer Duty", area: "conduct", short: "FCA's PRIN 12 — outcomes-based conduct regulation.", long: "Four outcomes: products & services · price & value · consumer understanding · consumer support. Plus three cross-cutting rules: act in good faith, avoid foreseeable harm, enable customers to pursue their objectives. Senior Manager attestation required annually." },
  { term: "TCF", area: "conduct", short: "Treating Customers Fairly.", long: "FCA's pre-2023 framework — six outcomes. Largely subsumed by Consumer Duty but the principles still appear in supervisory discussions." },
  { term: "FOS", area: "conduct", short: "Financial Ombudsman Service.", long: "Independent body for resolving disputes between consumers and financial firms. Decisions are binding on firms (up to £430k as of 2026). DISP rules cover complaint handling; firms have 8 weeks to resolve." },
  { term: "Vulnerable customer", area: "conduct", short: "Drivers from FCA FG21/1.", long: "Four drivers: health · life events · resilience · capability. Firms must identify, treat appropriately, train staff, and monitor outcomes for vulnerable customers — across the whole customer base, not just opt-in." },
  { term: "Fair value assessment", area: "conduct", short: "Required for every retail product under Consumer Duty.", long: "Documented assessment that the price represents fair value relative to the benefit. Must consider total costs (including non-financial), the target market, and vulnerable customer impact. Reviewed at least annually." },

  // AML / Financial Crime
  { term: "MLRO", area: "aml", short: "Money Laundering Reporting Officer.", long: "Senior Manager Function (SMF17 in FCA-regulated firms). Personally accountable for the firm's AML programme, SAR decisions, and regulatory reporting. The role with the highest personal liability in compliance." },
  { term: "SAR", area: "aml", short: "Suspicious Activity Report.", long: "Filed with the National Crime Agency under POCA 2002 or TACT 2000 when there is knowledge or suspicion of money laundering / terrorist financing. Failing to file when required is a criminal offence." },
  { term: "CDD", area: "aml", short: "Customer Due Diligence.", long: "Risk-based identification and verification of customers and beneficial owners. Required under MLR 2017. Triggers include onboarding, changes in circumstance, and periodic refresh based on risk rating." },
  { term: "EDD", area: "aml", short: "Enhanced Due Diligence.", long: "Additional CDD measures for high-risk situations: PEPs, high-risk jurisdictions, complex/unusual transactions. Source-of-funds AND source-of-wealth typically required." },
  { term: "PEP", area: "aml", short: "Politically Exposed Person.", long: "Individual entrusted with prominent public functions (and their family members / close associates). UK guidance treats UK domestic PEPs at lower risk than foreign PEPs by default — but EDD obligations still apply." },
  { term: "DAML", area: "aml", short: "Defence Against Money Laundering.", long: "A reporter's request to the NCA for consent to proceed with a transaction that would otherwise constitute a money-laundering offence. NCA has 7 working days to respond; if no response, consent is deemed given." },
  { term: "FATF", area: "aml", short: "Financial Action Task Force.", long: "Intergovernmental body setting global AML/CTF/CPF standards. Issues the 40 Recommendations; conducts mutual evaluations of member countries. UK's last MER was 2018." },
  { term: "OFSI", area: "aml", short: "Office of Financial Sanctions Implementation.", long: "Part of HM Treasury. Administers UK financial sanctions, issues licences, and enforces breaches. Maintains the UK Sanctions List." },
  { term: "POCA", area: "aml", short: "Proceeds of Crime Act 2002.", long: "Primary UK statute on money laundering. Key offences: concealing (s.327), arranging (s.328), acquiring/using/possessing (s.329). 'Failure to disclose' offences in s.330–s.332 apply in the regulated sector." },
];
